# Récupère tous les hébergements
GET http://localhost:3000/accommodations

# Pagination
GET http://localhost:3000/accommodations?limit=2&page=4

# Récupère les hébergements associés à un propriétaire
GET http://localhost:3000/accommodations/11aa2a70-d409-4961-8f14-ddb84a225ddf

# Récupère un hébergement par son identifiant
GET http://localhost:3000/accommodations/single/22b9d031-0419-4e0c-8398-1c2aa7c87e03


