DELETE http://localhost:3000/accommodations/1a17423f-5d3b-4adc-814a-c1e58e8ecfb4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMTkzYzllYi1jZTJlLTQ5MWEtYmNjYS0xMTA5MGNjOTkwYTMiLCJlbWFpbCI6InRvbUBtYWlsLmZyIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NTYwNjQ4MDIsImV4cCI6MTc1NjA2ODQwMiwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.u5-14RR2B1UJpHnlnLYYJQhekxWdWyHTJw_XM7Ggh-0
