# Récupère tous les hébergements
GET http://localhost:3000/accommodations

# Pagination
GET http://localhost:3000/accommodations?limit=2&page=4

# Récupère les hébergements associés à un propriétaire
GET http://localhost:3000/accommodations/82adc5d4-7ded-49ce-a264-120f2fba3bfa

# Récupère un hébergement par son identifiant
GET http://localhost:3000/accommodations/single/e80887f5-8fe2-45ef-a60e-f9a656a806f0


