PATCH http://localhost:3000/accommodations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4MmFkYzVkNC03ZGVkLTQ5Y2UtYTI2NC0xMjBmMmZiYTNiZmEiLCJlbWFpbCI6InVzZXJAbWFpbC5mciIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzU0NzIxMDA3LCJleHAiOjE3NTQ3MjQ2MDcsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.pte__xiG7CCsw8eqDMLDCoGXOzytkZEahqMww3AugMI
{
    "id": "e80887f5-8fe2-45ef-a60e-f9a656a806f0",
    "name": "Test2"
}
