DELETE http://localhost:3000/events/43dbeb7c-810f-494a-a0ce-b138f796dc97
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwYmZmZDI1Ni0xNGNhLTQ0NGMtOTk1Ny1mNWM1MjQ3MTczNWYiLCJlbWFpbCI6ImxvdWlzQG1haWwuZnIiLCJyb2xlIjoidXNlciIsImlhdCI6MTc1NjI3NjE2MiwiZXhwIjoxNzU2Mjc5NzYyLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.N5upTAE6jaeHbFGPrkG5S5YR5tjfY8lnhimeriptB8c
