

# Récupère tous les événements
GET http://localhost:3000/events

# Pagination
GET http://localhost:3000/events?limit=2&page=1

# Récupère les événements associés à un propriétaire
GET http://localhost:3000/events/23c53520-dee4-40f6-9dcd-63ed818b51a4

# Récupère les événements à partir d'une rangée de date
GET http://localhost:3000/events
    ?startDate=Mon May 12 2025 18:00:30
    &endDate=Mon May 12 2025 22:00:00

# Récupère un événement par son identifiant
GET http://localhost:3000/events/single/430bf9cd-5aad-4289-b4ef-762789dd6433


