# Récupère tous les sites touristiques
GET http://localhost:3000/places

# Pagination
GET http://localhost:3000/places?limit=2&page=1

# Récupère les sites touristiques associés à un propriétaire
GET http://localhost:3000/places/23c53520-dee4-40f6-9dcd-63ed818b51a4

# Récupère un site touristique par son identifiant
GET http://localhost:3000/places/single/2ab8118e-6989-4515-b408-963759d759c2


