PATCH http://localhost:3000/places
Content-Type: application/json

{
    "id": "76482ca5-6288-4568-b069-72a5ea2cab2b",
    "type": "museum",
    "address": "12 Rue de la République, 13001 Marseille"
}
