PATCH http://localhost:3000/places
Content-Type: application/json

{
    "id": "76482ca5-6288-4568-b069-72a5ea2cab2b",
    "type": "museum",
    "address": "275 boulevard François 1er, 76600 Le Havre"
}
