DELETE http://localhost:3000/places/83319e79-15a5-4732-b116-51557236e2cb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwYmZmZDI1Ni0xNGNhLTQ0NGMtOTk1Ny1mNWM1MjQ3MTczNWYiLCJlbWFpbCI6ImxvdWlzQG1haWwuZnIiLCJyb2xlIjoidXNlciIsImlhdCI6MTc1NjI3NjE2MiwiZXhwIjoxNzU2Mjc5NzYyLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.N5upTAE6jaeHbFGPrkG5S5YR5tjfY8lnhimeriptB8c
