POST http://localhost:3000/places
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwYmZmZDI1Ni0xNGNhLTQ0NGMtOTk1Ny1mNWM1MjQ3MTczNWYiLCJlbWFpbCI6ImxvdWlzQG1haWwuZnIiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTYzMTMzNTYsImV4cCI6MTc1NjMxNjk1NiwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.LTHKYVNFppsa7-NLKE9AdtQ_n-rSOWr-gnb30QjRVy0


{
    "name": "Musée d'Art Moderne de Céret",
    "description": "Un musée emblématique dédié aux artistes du XXe siècle.",
    "type": "museum",
    "address": "8 Bd Maréchal Joffre, Céret (66400)",
    "priceRange": "0-0",
    "languages" : ["fr", "en", "es"],
    "requiredAge": 0,
    "from": 2,
    "to": 6,
    "open": "10:00",
    "close": "18:00"
}


# Route réservée aux administrateurs
POST http://localhost:3000/places/create-many
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwYmZmZDI1Ni0xNGNhLTQ0NGMtOTk1Ny1mNWM1MjQ3MTczNWYiLCJlbWFpbCI6ImxvdWlzQG1haWwuZnIiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTYzMTMzNTYsImV4cCI6MTc1NjMxNjk1NiwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.LTHKYVNFppsa7-NLKE9AdtQ_n-rSOWr-gnb30QjRVy0

{"places" : [
  {
    "name": "Jardin des Plantes de Montpellier",
    "description": "Un jardin botanique historique fondé au XVIe siècle.",
    "type": "garden",
    "address": "Blvd Henri IV, 34000 Montpellier",
    "priceRange": "0-0",
    "languages": ["fr", "en"],
    "requiredAge": 0,
    "from": 1,
    "to": 6,
    "open": "08:00",
    "close": "18:30",
    "ownerId": "4758e828-489b-495d-9c02-8d897565a702"

  },
  {
    "name": "Plage de l’Ouille",
    "description": "Une plage sauvage et discrète entre Collioure et Argelès.",
    "type": "beach",
    "address": "Chemin de la Galère, 66700 Argelès-sur-Mer",
    "priceRange": "0-0",
    "languages": ["fr", "en"],
    "requiredAge": 0,
    "from": 1,
    "to": 6,
    "open": "07:00",
    "close": "21:00",
    "ownerId": "4758e828-489b-495d-9c02-8d897565a702"

  },
  {
    "name": "Parc de Valmy",
    "description": "Parc ombragé avec vue sur la mer et aires de pique-nique.",
    "type": "park",
    "address": "Chemin de Valmy, 66700 Argelès-sur-Mer",
    "priceRange": "0-0",
    "languages": ["fr", "en", "de"],
    "requiredAge": 0,
    "from": 1,
    "to": 6,
    "open": "08:00",
    "close": "20:00",
    "ownerId": "4758e828-489b-495d-9c02-8d897565a702"

  },
  {
    "name": "Fort Saint-Elme",
    "description": "Fort militaire surplombant la baie de Collioure.",
    "type": "historic_site",
    "address": "Chemin du Fort, 66190 Collioure",
    "priceRange": "8-10",
    "languages": ["fr", "en", "es"],
    "requiredAge": 0,
    "from": 3,
    "to": 6,
    "open": "10:30",
    "close": "18:30",
    "ownerId": "4758e828-489b-495d-9c02-8d897565a702"

  },
  {
    "name": "Théâtre de l’Archipel",
    "description": "Scène nationale à l’architecture audacieuse.",
    "type": "theater",
    "address": "Avenue Général Leclerc, 66000 Perpignan",
    "priceRange": "10-40",
    "languages": ["fr", "es"],
    "requiredAge": 6,
    "from": 3,
    "to": 6,
    "open": "14:00",
    "close": "22:00",
    "ownerId": "4758e828-489b-495d-9c02-8d897565a702"

  },
  {
    "name": "Bibliothèque Louis Nucéra",
    "description": "Grande médiathèque moderne au cœur de Nice.",
    "type": "library",
    "address": "2 Place Yves Klein, 06300 Nice",
    "priceRange": "0-0",
    "languages": ["fr", "en", "it"],
    "requiredAge": 0,
    "from": 2,
    "to": 6,
    "open": "09:00",
    "close": "19:00",
    "ownerId": "4758e828-489b-495d-9c02-8d897565a702"

  },
  {
    "name": "Monument aux Morts du Plateau de Glières",
    "description": "Lieu de mémoire de la Résistance en Haute-Savoie.",
    "type": "monument",
    "address": "Plateau des Glières, 74570 Thorens-Glières",
    "priceRange": "0-0",
    "languages": ["fr", "en"],
    "requiredAge": 0,
    "from": 3,
    "to": 6,
    "open": "09:00",
    "close": "17:00",
    "ownerId": "4758e828-489b-495d-9c02-8d897565a702"

  },
  {
    "name": "Zoo de la Barben",
    "description": "Un des plus grands zoos du sud de la France.",
    "type": "zoo",
    "address": "Route du Château, 13330 La Barben",
    "priceRange": "12-20",
    "languages": ["fr", "en", "nl"],
    "requiredAge": 0,
    "from": 2,
    "to": 6,
    "open": "09:30",
    "close": "18:00",
    "ownerId": "4758e828-489b-495d-9c02-8d897565a702"

  },
  {
    "name": "Marché couvert de Narbonne",
    "description": "Marché alimentaire animé dans une halle Belle Époque.",
    "type": "marketplace",
    "address": "1 Boulevard Dr Ferroul, 11100 Narbonne",
    "priceRange": "0-0",
    "languages": ["fr", "en", "es"],
    "requiredAge": 0,
    "from": 1,
    "to": 6,
    "open": "07:00",
    "close": "13:30",
    "ownerId": "4758e828-489b-495d-9c02-8d897565a702"

  }
]

}
