# Récupère tous les sites touristiques
GET http://localhost:3000/places

# Pagination
GET http://localhost:3000/places?limit=2&page=1

# Récupère les sites touristiques associés à un propriétaire
GET http://localhost:3000/places/11aa2a70-d409-4961-8f14-ddb84a225ddf

# Récupère un site touristique par son identifiant
GET http://localhost:3000/places/single/338749b1-c72e-4fd1-9c13-764c9e69ea2d


