# Récupère toutes les activités
GET http://localhost:3000/activities

# Pagination
GET http://localhost:3000/activities?limit=2&page=1

# Récupère les activités associés à un propriétaire
GET http://localhost:3000/activities/11aa2a70-d409-4961-8f14-ddb84a225ddf

# Récupère une activité par son identifiant
GET http://localhost:3000/activities/single/0f0cf7b9-843f-4013-a387-08fc2adec825


