# Récupère toutes les activités
GET http://localhost:3000/activities

# Pagination
GET http://localhost:3000/activities?limit=2&page=3

# Récupère les activités associés à un propriétaire
GET http://localhost:3000/activities/23c53520-dee4-40f6-9dcd-63ed818b51a4

# Récupère une activité par son identifiant
GET http://localhost:3000/activities/single/9d310bb0-566c-4ebe-9093-11ff391a27e0


