POST http://localhost:3000/activities
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwYmZmZDI1Ni0xNGNhLTQ0NGMtOTk1Ny1mNWM1MjQ3MTczNWYiLCJlbWFpbCI6ImxvdWlzQG1haWwuZnIiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTYzMTMzNTYsImV4cCI6MTc1NjMxNjk1NiwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.LTHKYVNFppsa7-NLKE9AdtQ_n-rSOWr-gnb30QjRVy0

{
    "name": "Balade paddle dans la baie",
    "description": "Découvrez les criques en paddle encadré par un moniteur diplômé.",
    "type": "nautical_sport",
    "address": "10 Rue de la Paix, 75002 Paris, France",
    "priceRange": "50-80",
    "duration": 2,
    "requiredAge": 10,
    "languages": ["en", "fr"],
    "from": 2,
    "to": 5,
    "open": "10:00",
    "close": "18:00"
}


# Route réservée aux administrateurs
POST http://localhost:3000/activities/create-many
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwYmZmZDI1Ni0xNGNhLTQ0NGMtOTk1Ny1mNWM1MjQ3MTczNWYiLCJlbWFpbCI6ImxvdWlzQG1haWwuZnIiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTYzMTMzNTYsImV4cCI6MTc1NjMxNjk1NiwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.LTHKYVNFppsa7-NLKE9AdtQ_n-rSOWr-gnb30QjRVy0


{"activities" : [
  {
    "name": "Randonnée guidée en montagne",
    "description": "Explorez les sentiers avec un guide local passionné.",
    "type": "hiking",
    "duration": 4,
    "priceRange": "30-60",
    "address": "Chemin des Crêtes, Font-Romeu, Pyrénées-Orientales",
    "languages": ["fr"],
    "requiredAge": 12,
    "from": 1,
    "to": 5,
    "open": "08:00",
    "close": "16:00",
    "ownerId": "0bffd256-14ca-444c-9957-f5c52471735f"

},
  {
    "name": "Cours de cuisine catalane",
    "description": "Apprenez à préparer des plats traditionnels catalans.",
    "type": "cooking_class",
    "duration": 3,
    "priceRange": "40-70",
    "address": "45 avenue de la République, 66000 Perpignan",
    "languages": ["fr", "en", "es"],
    "requiredAge": 16,
    "from": 3,
    "to": 6,
    "open": "14:00",
    "close": "17:00",
    "ownerId": "0bffd256-14ca-444c-9957-f5c52471735f"
  },
  {
    "name": "Visite historique du centre-ville",
    "description": "Découvrez l’histoire locale avec un guide expert.",
    "type": "cultural_tour",
    "duration": 1,
    "priceRange": "15-25",
    "address": "Place de la Révolution Française, 66190 Collioure",
    "languages": ["fr", "en"],
    "requiredAge": 0,
    "from": 1,
    "to": 6,
    "open": "10:00",
    "close": "18:00",
    "ownerId": "0bffd256-14ca-444c-9957-f5c52471735f"

  },
  {
    "name": "Initiation au kite surf",
    "description": "Premiers pas en kite surf avec un moniteur qualifié.",
    "type": "nautical_sport",
    "duration": 2,
    "priceRange": "70-120",
    "address": "Route de Leucate‑plage, 11370 Leucate",
    "languages": ["fr", "en"],
    "requiredAge": 14,
    "from": 3,
    "to": 6,
    "open": "09:00",
    "close": "17:00",
    "ownerId": "0bffd256-14ca-444c-9957-f5c52471735f"

  },
  {
    "name": "Atelier de poterie artisanale",
    "description": "Créez vos propres pièces en argile.",
    "type": "art_craft",
    "duration": 2,
    "priceRange": "30-45",
    "address": "24 rue du Puig Carroitg, 66290 Cerbère",
    "languages": ["fr", "en"],
    "requiredAge": 10,
    "from": 5,
    "to": 6,
    "open": "10:00",
    "close": "16:00",
    "ownerId": "0bffd256-14ca-444c-9957-f5c52471735f"
  },
  {
    "name": "Découverte de la faune marine en snorkeling",
    "description": "Explorez la vie sous‑marine avec un guide expérimenté.",
    "type": "nautical_sport",
    "duration": 2,
    "priceRange": "55-90",
    "address": "Plage de la Marenda, 66700 Argelès‑sur‑Mer",
    "languages": ["fr", "en"],
    "requiredAge": 12,
    "from": 2,
    "to": 6,
    "open": "10:00",
    "close": "18:00",
    "ownerId": "0bffd256-14ca-444c-9957-f5c52471735f"
  },
  {
    "name": "Dégustation de vins locaux",
    "description": "Goûtez aux meilleurs vins du Roussillon avec un sommelier.",
    "type": "food_and_drink",
    "duration": 1,
    "priceRange": "20-40",
    "address": "Domaine des Vignes, 11510 Fitou",
    "languages": ["fr", "en"],
    "requiredAge": 18,
    "from": 4,
    "to": 6,
    "open": "14:00",
    "close": "19:00",
    "ownerId": "0bffd256-14ca-444c-9957-f5c52471735f"
  },
  {
    "name": "Balade à vélo le long de la côte",
    "description": "Parcourez la côte avec un guide local.",
    "type": "cycling",
    "duration": 3,
    "priceRange": "25-50",
    "address": "Promenade du Littoral, 66650 Banyuls‑sur‑Mer",
    "languages": ["fr"],
    "requiredAge": 8,
    "from": 1,
    "to": 5,
    "open": "09:00",
    "close": "15:00",
    "ownerId": "0bffd256-14ca-444c-9957-f5c52471735f"
  }
]

}
