PATCH http://localhost:3000/activities/1a17423f-5d3b-4adc-814a-c1e58e8ecfb4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyOWYxMzA0Ny03MTI1LTRlOWYtYjVhNC0wYTE4Yzk5ODRhZTkiLCJlbWFpbCI6Implc3N5QG1haWwuZnIiLCJyb2xlIjoidXNlciIsImlhdCI6MTc1NjA2Mzk1MSwiZXhwIjoxNzU2MDY3NTUxLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.ORFa6X0VMqmFVdMnk2qIdQgKZDhbYZ6ACl_YvQ3GI9c

{
    "languages": ["fr", "es"],
    "address": "10 Quai de la Mégisserie, 75001 Paris"
}
