POST http://localhost:3000/uploads/file
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryXYZ
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyM2M1MzUyMC1kZWU0LTQwZjYtOWRjZC02M2VkODE4YjUxYTQiLCJlbWFpbCI6ImNvbnRhY3RAYmlzdHJvZGVseW9uLmZyIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NTYyMzMwNTAsImV4cCI6MTc1NjIzNjY1MCwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.eHoNLCSdqLEfSLKO09xmgVxKdIBWE7ECauZXh9UXthY


------WebKitFormBoundaryXYZ
Content-Disposition: form-data; name="file"; filename="test-image.jpg"
Content-Type: image/jpeg

< C:\Users\Louis\Documents\programming\web\Back\Nodejs\nest\api-tourisme\src\uploads\http\test-image.jpg
------WebKitFormBoundaryXYZ--
