# Récupère tous les restaurants
GET http://localhost:3000/restaurants

# Pagination
GET http://localhost:3000/restaurants?limit=2&page=1

# Récupère les restaurants associés à un propriétaire
GET http://localhost:3000/restaurants/614e0d8f-478a-4b07-8bf9-34decd750417

# Récupère un restaurant par son identifiant
GET http://localhost:3000/restaurants/single/d611fa2c-581e-4cb8-b38d-894486d7909c


