PATCH http://localhost:3000/restaurants
Content-Type: application/json

{
    "id": "d611fa2c-581e-4cb8-b38d-894486d7909c",
    "type": "bistro",
    "address": "12 Rue de la République, 13001 Marseille"
}
