# Récupère tous les restaurants
GET http://localhost:3000/restaurants

# Pagination
GET http://localhost:3000/restaurants?limit=2&page=1

# Récupère les restaurants associés à un propriétaire
GET http://localhost:3000/restaurants/11aa2a70-d409-4961-8f14-ddb84a225ddf

# Récupère un restaurant par son identifiant
GET http://localhost:3000/restaurants/single/1ad71fb6-da59-42d2-85c8-45d4e136f8a2


