PATCH http://localhost:3000/owners
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyM2M1MzUyMC1kZWU0LTQwZjYtOWRjZC02M2VkODE4YjUxYTQiLCJlbWFpbCI6ImNvbnRhY3RAYmlzdHJvZGVseW9uLmZyIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NTYyNzQ1MDQsImV4cCI6MTc1NjI3ODEwNCwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.qqNEdcUnri833T8hy2rAfy2seLx_elkAezYk194Je7Q

{
    "id": "23c53520-dee4-40f6-9dcd-63ed818b51a4",
    "websiteUrl": "http://cie-site.fr"
}
