POST http://localhost:3000/owners
Content-Type: application/json

{
    "name": "luana",
    "phoneNumber": "+33479551234",
    "password": "luana1234!",
    "email": "luana@mail.fr",
    "websiteUrl": "https://user.fr"
}


POST http://localhost:3000/owners/create-many
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YWUxZGIwNy1mZGU1LTRhZDktOGM5YS03MmNmOWZmZWVmYzkiLCJlbWFpbCI6InRlc3RAbWFpbC5mciIsImlhdCI6MTc1NDQyMzc3OCwiZXhwIjoxNzU0NDI3Mzc4LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.4eeG8871jC-x0JCYnJxtF57BTklBdvY--UAP3d4lXlk
{"owners" : [{
    "name": "Test1",
    "phoneNumber": "+33479551234",
    "email": "test1@mail.fr",
    "password": "MontagneAventure1234!",
    "websiteUrl": "https://montagneaventure.fr" }
,
  {
    "name": "Test2",
    "phoneNumber": "+33688997755",
    "email": "test2@mail.fr",
    "websiteUrl": "https://randospyrenees.fr",
    "password": "RandoPyrenees1234!"
  },
  {
    "name": "Test 3",
    "phoneNumber": "+33344668899",
    "email": "test3@mail.fr",
    "password": "TerresSauvages1234!",
    "websiteUrl": "https://terressauvages.fr"
  }
]
}
