POST http://localhost:3000/owners
Content-Type: application/json

  {
    "name": "Bistro de Lyon",
    "phoneNumber": "+33478235612",
    "password": "Bistrodelyon1234!",
    "email": "contact@bistrodelyon.fr",
    "websiteUrl": "https://www.bistrodelyon.fr"
  }

## Route réservée aux administrateurs
POST http://localhost:3000/owners/create-many
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyM2M1MzUyMC1kZWU0LTQwZjYtOWRjZC02M2VkODE4YjUxYTQiLCJlbWFpbCI6ImNvbnRhY3RAYmlzdHJvZGVseW9uLmZyIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NTYyNzQ1MDQsImV4cCI6MTc1NjI3ODEwNCwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.qqNEdcUnri833T8hy2rAfy2seLx_elkAezYk194Je7Q

{"owners" : [{
    "name": "Hôtel Belle Vue",
    "phoneNumber": "+33559234567",
    "password": "Hôtelbellevue1234!",
    "email": "reservation@hotelbellevue.fr",
    "websiteUrl": "https://www.hotelbellevue.fr"
  },
  {
    "name": "Musée d’Art Moderne de Lille",
    "phoneNumber": "+33320067890",
    "password": "Muséedartmodernedelille!",
    "email": "info@mamlille.fr",
    "websiteUrl": "https://www.mamlille.fr"
  },
  {
    "name": "Festival des Lumières de Lyon",
    "phoneNumber": "+33472324588",
    "password": "Festivaldeslumieresdelyon1234!",
    "email": "orga@lumiereslyon.fr",
    "websiteUrl": "https://www.lumiereslyon.fr"
  },
  {
    "name": "Aventure Canoë Ardèche",
    "phoneNumber": "+33475392011",
    "password": "Aventurecanoeardeche1234!",
    "email": "contact@canoe-ardeche.fr",
    "websiteUrl": "https://www.canoe-ardeche.fr"
  }
]
}
